In [74]:
" Created by Paul A. Gureghian on 9/4/2018 " 

' Created by Paul A. Gureghian on 9/4/2018 '

In [75]:
" Data splitting with Scikit-Learn "
" Using the train_test_split function for data analysis as part of a Machine Learning project "

' Using the train_test_split function for data analysis as part of a Machine Learning project '

In [76]:
" You should split your dataset before you begin modeling "
" First fit the model on the training set, then estimate your model performance with the testing set "

' First fit the model on the training set, then estimate your model performance with the testing set '

In [77]:
# import packages 

import numpy as np 
from sklearn.model_selection import KFold
import sklearn.model_selection as model_selection 
import sklearn.cross_validation as cross_validation 

In [78]:
# define X for features 

X = list(range(10)) 
print(X) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [79]:
# define y for labels 

y = [x * x for x in X] 
print(y) 

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [80]:
# split data into two sets 

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size =0.75, test_size =0.25, random_state =101)
print("X_train: ", X_train)
print("y_train: ", y_train)
print("X_test: ", X_test)
print("y_test: ", y_test) 

X_train:  [4, 9, 3, 5, 7, 6, 1]
y_train:  [16, 81, 9, 25, 49, 36, 1]
X_test:  [8, 2, 0]
y_test:  [64, 4, 0]


In [81]:
# split data the old way 

X_train, X_test, y_test, y_train = cross_validation.train_test_split(X, y, train_size =0.75, test_size =0.25, random_state =101)
print("X_train: ", X_train)
print("y_train: ", y_train)
print("X_test: ", X_test)
print("y_train: ", y_train) 

X_train:  [4, 9, 3, 5, 7, 6, 1]
y_train:  [64, 4, 0]
X_test:  [8, 2, 0]
y_train:  [64, 4, 0]


In [83]:
# split data into n consecutive folds with the KFold() function

kf = KFold(n_splits=5, shuffle =True) 
X = np.array(X)
y = np.array(y) 
print(X)
print(y) 
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    print("X_test: ", X_test) 



[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
X_test:  [5 7]
X_test:  [0 4]
X_test:  [3 8]
X_test:  [1 9]
X_test:  [2 6]


In [84]:
X_train


array([0, 1, 3, 4, 5, 7, 8, 9])

In [85]:
X_test

array([2, 6])

In [86]:
y_train 

array([ 0,  1,  9, 16, 25, 49, 64, 81])

In [87]:
y_test 

array([ 4, 36])